# Generated by Django 5.0 on 2024-01-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameModel(
            old_name='Stanzas',
            new_name='Stanza',
        ),
        migrations.RenameModel(
            old_name='TextDecorations',
            new_name='TextDecoration',
        ),
        migrations.RenameModel(
            old_name='ViewerNotes',
            new_name='ViewerNote',
        ),
    ]
