# Generated by Django 5.0 on 2024-01-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0002_rename_details_detail_rename_stanzas_stanza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlemanuscript',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='singlemanuscript',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
