# Generated by Django 5.0 on 2024-01-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0003_singlemanuscript_name_alter_singlemanuscript_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlemanuscript',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.manuscriptlocation'),
        ),
    ]
