# Generated by Django 5.0.2 on 2024-11-19 20:14

import django.utils.timezone
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("textannotation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textannotation",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="textannotation",
            name="end_index",
        ),
        migrations.RemoveField(
            model_name="textannotation",
            name="field_name",
        ),
        migrations.RemoveField(
            model_name="textannotation",
            name="start_index",
        ),
        migrations.AddField(
            model_name="textannotation",
            name="annotation_type",
            field=models.CharField(
                choices=[
                    ("note", "Editorial Note"),
                    ("translation", "Translation"),
                    ("variant", "Textual Variant"),
                    ("reference", "Cross Reference"),
                ],
                default="note",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="textannotation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="textannotation",
            name="from_pos",
            field=models.JSONField(
                default=dict, help_text="ProseMirror position data for annotation start"
            ),
        ),
        migrations.AddField(
            model_name="textannotation",
            name="selected_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="textannotation",
            name="to_pos",
            field=models.JSONField(
                default=dict, help_text="ProseMirror position data for annotation end"
            ),
        ),
        migrations.AddField(
            model_name="textannotation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="textannotation",
            name="annotation",
            field=prose.fields.RichTextField(
                blank=True, help_text="Enter your annotation here", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="textannotation",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="textannotat_content_d0791f_idx",
            ),
        ),
    ]
