# Generated by Django 5.0.2 on 2024-08-27 19:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="team",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
