# Generated by Django 5.0.2 on 2025-02-25 21:12

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_sitepage_delete_specificationspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', wagtail.fields.RichTextField()),
            ],
        ),
    ]
