# Generated by Django 5.0.2 on 2024-02-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('authority_file', models.URLField(blank=True, help_text="The URL to the authority file for the location. If there isn't one, leave blank.", max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='singlemanuscript',
            name='authority_file',
            field=models.URLField(blank=True, help_text="The URL to the authority file for the manuscript. If there isn't one, leave blank.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='singlemanuscript',
            name='iiif_url',
            field=models.URLField(blank=True, help_text="The URL to the IIIF manifest for the manuscript. If there isn't one, leave blank.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='singlemanuscript',
            name='manuscript_destroyed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlemanuscript',
            name='manuscript_lost',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlemanuscript',
            name='provenance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singlemanuscript',
            name='viewer_notes',
            field=models.ForeignKey(blank=True, help_text='Notes by whomever viewed the manuscript.', null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscript.viewernote'),
        ),
        migrations.AddField(
            model_name='stanza',
            name='locations_mentioned',
            field=models.ManyToManyField(blank=True, help_text='Locations mentioned in the stanza.', null=True, to='manuscript.location'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('page_notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='The image of the page from the manuscript.', null=True, upload_to='')),
                ('manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manuscript.singlemanuscript')),
                ('stanzas', models.ManyToManyField(blank=True, null=True, to='manuscript.stanza')),
            ],
        ),
    ]
