# Generated by Django 5.0.2 on 2024-02-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0002_location_singlemanuscript_authority_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='stanzas',
            field=models.ManyToManyField(blank=True, to='manuscript.stanza'),
        ),
        migrations.AlterField(
            model_name='stanza',
            name='locations_mentioned',
            field=models.ManyToManyField(blank=True, help_text='Locations mentioned in the stanza.', to='manuscript.location'),
        ),
    ]
