# Generated by Django 5.0.2 on 2024-02-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0004_singlemanuscript_purl_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewernote",
            name="related_manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="manuscript.singlemanuscript",
            ),
        ),
    ]
