# Generated by Django 5.0.2 on 2024-02-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0006_alter_viewernote_viewer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codex",
            options={"verbose_name_plural": "Codex"},
        ),
        migrations.AlterModelOptions(
            name="editorialstatus",
            options={
                "verbose_name": "Editorial Status",
                "verbose_name_plural": "Editorial Status",
            },
        ),
        migrations.AlterModelOptions(
            name="library",
            options={"verbose_name_plural": "Libraries"},
        ),
        migrations.AlterModelOptions(
            name="manuscriptlocation",
            options={"verbose_name": "Manuscript Location"},
        ),
        migrations.AlterModelOptions(
            name="singlemanuscript",
            options={"verbose_name": "Manuscript"},
        ),
        migrations.RemoveField(
            model_name="singlemanuscript",
            name="codex",
        ),
        migrations.RemoveField(
            model_name="singlemanuscript",
            name="viewer_notes",
        ),
        migrations.AddField(
            model_name="codex",
            name="related_manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="manuscript.singlemanuscript",
            ),
        ),
        migrations.AlterField(
            model_name="singlemanuscript",
            name="purl_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the permanent URL for the manuscript. If there isn't one, leave blank.",
                null=True,
                verbose_name="PURL",
            ),
        ),
    ]
