# Generated by Django 5.0.2 on 2024-02-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "manuscript",
            "0007_alter_codex_options_alter_editorialstatus_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="manuscript.singlemanuscript",
            ),
        ),
        migrations.AlterField(
            model_name="folio",
            name="iiif_url",
            field=models.URLField(
                blank=True,
                help_text="Provide a IIIF manifest to a page in the manuscript. If there isn't one, leave blank.",
                null=True,
                verbose_name="IIIF URL",
            ),
        ),
        migrations.AlterField(
            model_name="singlemanuscript",
            name="iiif_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the IIIF manifest for the manuscript. If there isn't one, leave blank.",
                max_length=255,
                null=True,
                verbose_name="IIIF URL",
            ),
        ),
    ]
