# Generated by Django 5.0.2 on 2024-02-21 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0009_remove_singlemanuscript_manuscript_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stanza",
            name="related_folio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="manuscript.folio",
            ),
        ),
    ]
