# Generated by Django 5.0.2 on 2024-02-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0011_remove_folio_stanzas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="folio",
            old_name="page_notes",
            new_name="folio_notes",
        ),
        migrations.RenameField(
            model_name="folio",
            old_name="page_number",
            new_name="folio_number",
        ),
    ]
