# Generated by Django 5.0.2 on 2024-03-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0012_rename_page_notes_folio_folio_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlemanuscript",
            name="gazetteer_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to an external gazetteer for the manuscript. If there isn't one, leave blank.",
                max_length=255,
                null=True,
                verbose_name="Gazetteer URL",
            ),
        ),
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_number_on_page",
            field=models.IntegerField(
                blank=True,
                help_text="The line number of the stanza on the folio in the manuscript.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="singlemanuscript",
            name="authority_file",
            field=models.URLField(
                blank=True,
                help_text="The URL to the authority file for the manuscript. If there isn't one, leave blank.",
                max_length=255,
                null=True,
                verbose_name="Authority File",
            ),
        ),
        migrations.AlterField(
            model_name="singlemanuscript",
            name="purl_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the permanent URL for the manuscript. If there isn't one, leave blank.",
                null=True,
                verbose_name="Permanent URL",
            ),
        ),
        migrations.AlterField(
            model_name="stanza",
            name="stanza_number",
            field=models.IntegerField(
                blank=True,
                help_text="The number of the stanza in the manuscript.",
                null=True,
            ),
        ),
    ]
