# Generated by Django 5.0.2 on 2024-03-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0013_singlemanuscript_gazetteer_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detail",
            old_name="book_headigs_notes",
            new_name="book_headings_notes",
        ),
    ]
