# Generated by Django 5.0.2 on 2024-03-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0014_rename_book_headigs_notes_detail_book_headings_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city', 'country'], 'verbose_name': 'Toponym', 'verbose_name_plural': 'Toponyms'},
        ),
        migrations.AddField(
            model_name='editorialstatus',
            name='iiif_url',
            field=models.URLField(blank=True, help_text="The URL to the IIIF manifest for the manuscript. If there isn't one, leave blank.", max_length=255, null=True, verbose_name='IIIF URL'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'country')},
        ),
    ]
