# Generated by Django 5.0.2 on 2024-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0016_textdecoration_white_vine_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdecoration',
            name='diagrams',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textdecoration',
            name='illumination',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textdecoration',
            name='maps',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textdecoration',
            name='white_vine_work',
            field=models.CharField(blank=True, null=True),
        ),
    ]
