# Generated by Django 5.0.2 on 2024-03-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0017_alter_textdecoration_diagrams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialstatus',
            name='collated',
            field=models.CharField(blank=True, null=True),
        ),
    ]
