# Generated by Django 5.0.2 on 2024-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0020_dateseen_remove_viewernote_date_seen_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="singlemanuscript",
            old_name="authority_file",
            new_name="authority_file_url",
        ),
        migrations.RemoveField(
            model_name="manuscriptlocation",
            name="digitized_url",
        ),
        migrations.RemoveField(
            model_name="manuscriptlocation",
            name="shelfmark",
        ),
        migrations.RemoveField(
            model_name="singlemanuscript",
            name="name",
        ),
        migrations.AddField(
            model_name="singlemanuscript",
            name="digitized_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the digitized manuscript. If there isn't one, leave blank.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="singlemanuscript",
            name="shelfmark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
