# Generated by Django 5.0.2 on 2024-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manuscript",
            "0021_rename_authority_file_singlemanuscript_authority_file_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viewernote",
            name="dates_seen",
        ),
        migrations.AddField(
            model_name="viewernote",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="DateSeen",
        ),
    ]
