# Generated by Django 5.0.2 on 2024-04-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0022_remove_viewernote_dates_seen_viewernote_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detail",
            old_name="marginal_rubrics",
            new_name="stanza_headings_marginal_rubrics",
        ),
        migrations.RenameField(
            model_name="detail",
            old_name="marginal_rubrics_notes",
            new_name="stanza_headings_marginal_rubrics_notes",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="stanza_headings",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="stanza_headings_notes",
        ),
        migrations.RemoveField(
            model_name="editorialstatus",
            name="digitized",
        ),
        migrations.RemoveField(
            model_name="viewernote",
            name="viewer_initials",
        ),
        migrations.AlterField(
            model_name="detail",
            name="filigree_notes",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Flourished/Filigree Initials",
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="is_sea_red",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Is the Red Sea colored red?"
            ),
        ),
    ]
