# Generated by Django 5.0.2 on 2024-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manuscript",
            "0023_rename_marginal_rubrics_detail_stanza_headings_marginal_rubrics_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="stanza_headings_marginal_rubrics",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sh", "Stanza Headings"),
                    ("mr", "Marginal Rubrics"),
                    ("ne", "Neither"),
                    ("uk", "Unknown"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
