# Generated by Django 5.0.2 on 2024-04-01 19:28

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0024_alter_detail_stanza_headings_marginal_rubrics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["country"],
                "verbose_name": "Toponym",
                "verbose_name_plural": "Toponyms",
            },
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("country",)},
        ),
        migrations.AlterField(
            model_name="detail",
            name="abbreviations_notes",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="book_headings_notes",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="book_initials_notes",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="catchwords_notes",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="coat_of_arms_notes",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="distance_numbers_notes",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="map_labels_notes",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="stanza_headings_marginal_rubrics_notes",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="stanza_initials_notes",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Modern country"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="description",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="singlemanuscript",
            name="digitized_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the digitized manuscript. If there isn't one, leave blank.",
                max_length=255,
                null=True,
                verbose_name="Digitized URL",
            ),
        ),
        migrations.AlterField(
            model_name="singlemanuscript",
            name="provenance",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stanza",
            name="locations_mentioned",
            field=models.ManyToManyField(
                blank=True,
                help_text="Locations mentioned in the stanza.",
                to="manuscript.location",
                verbose_name="Associated toponyms",
            ),
        ),
        migrations.RemoveField(
            model_name="location",
            name="city",
        ),
        migrations.CreateModel(
            name="LocationAlias",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "placename_from_mss",
                    models.CharField(
                        blank=True,
                        help_text="The placename as it appears in the manuscript.",
                        max_length=255,
                        null=True,
                        verbose_name="Transcribed placename",
                    ),
                ),
                (
                    "placename_standardized",
                    models.CharField(
                        blank=True,
                        help_text="The standardized name of the placename.",
                        max_length=255,
                        null=True,
                        verbose_name="Standardized placename",
                    ),
                ),
                (
                    "placename_modern",
                    models.CharField(
                        blank=True,
                        help_text="The modern name of the placename.",
                        max_length=255,
                        null=True,
                        verbose_name="Modern placename",
                    ),
                ),
                (
                    "placename_alias",
                    models.CharField(
                        blank=True,
                        help_text="Additional aliases for the placename.",
                        max_length=255,
                        null=True,
                        verbose_name="Additional aliases",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manuscript.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Alias",
                "verbose_name_plural": "Location Aliases",
                "ordering": ["placename_standardized"],
                "unique_together": {("placename_standardized",)},
            },
        ),
    ]
