# Generated by Django 5.0.2 on 2024-04-01 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0025_alter_location_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanza",
            name="manuscript",
        ),
    ]
