# Generated by Django 5.0.2 on 2024-04-01 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0026_remove_stanza_manuscript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlemanuscript",
            name="library",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="manuscript.library",
            ),
        ),
    ]
