# Generated by Django 5.0.2 on 2024-04-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0028_alter_singlemanuscript_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folio",
            name="locations_mentioned",
            field=models.ManyToManyField(
                blank=True,
                help_text="Toponyms associated with the folio.",
                to="manuscript.location",
                verbose_name="Associated toponyms",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Latitude in decimal degrees. If left blank, the system will attempt to geocode the location from the modern placename.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Longitude in decimal degrees. If left blank, the system will attempt to geocode the location from the modern placename.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stanza",
            name="locations_mentioned",
            field=models.ManyToManyField(
                blank=True,
                help_text="Toponyms associated with the stanza.",
                to="manuscript.location",
                verbose_name="Associated toponyms",
            ),
        ),
    ]
