# Generated by Django 5.0.2 on 2024-04-16 14:41

from django.db import migrations, models

import manuscript.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manuscript",
            "0029_folio_locations_mentioned_alter_location_latitude_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanza",
            name="locations_mentioned",
        ),
        migrations.RemoveField(
            model_name="stanza",
            name="stanza_language",
        ),
        migrations.RemoveField(
            model_name="stanza",
            name="stanza_line_number_on_page",
        ),
        migrations.RemoveField(
            model_name="stanza",
            name="stanza_number",
        ),
        migrations.RemoveField(
            model_name="stanza",
            name="stanza_translation",
        ),
        migrations.RemoveField(
            model_name="stanza",
            name="stanza_translation_notes",
        ),
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_code",
            field=models.CharField(
                blank=True,
                help_text="Range of text on page by line numbers annotated by book-stanza-line number. For example: 01.01.01-01.01.07.",
                max_length=20,
                null=True,
                validators=[manuscript.models.validate_line_number_code],
            ),
        ),
        migrations.AddField(
            model_name="stanza",
            name="stanza_location",
            field=models.CharField(blank=True, null=True),
        ),
    ]
