# Generated by Django 5.0.2 on 2024-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0030_remove_stanza_locations_mentioned_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanza",
            name="stanza_location",
        ),
        migrations.AddField(
            model_name="folio",
            name="folio_includes_map",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("yes_toponyms", "Yes with toponyms"),
                    ("yes_no_toponyms", "Yes without toponyms"),
                    ("no", "No"),
                ],
                null=True,
            ),
        ),
    ]
