# Generated by Django 5.0.2 on 2024-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0031_remove_stanza_stanza_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_code_book",
            field=models.IntegerField(
                blank=True,
                help_text="The book number of the stanza.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_code_line",
            field=models.IntegerField(
                blank=True,
                help_text="The line number of the stanza.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_code_stanza",
            field=models.IntegerField(
                blank=True,
                help_text="The stanza number of the stanza.",
                max_length=2,
                null=True,
            ),
        ),
    ]
