# Generated by Django 5.0.2 on 2024-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0032_stanza_stanza_line_code_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stanza",
            name="stanza_line_code_book",
            field=models.IntegerField(
                blank=True, help_text="The book number of the stanza.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stanza",
            name="stanza_line_code_line",
            field=models.IntegerField(
                blank=True, help_text="The line number of the stanza.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stanza",
            name="stanza_line_code_stanza",
            field=models.IntegerField(
                blank=True, help_text="The stanza number of the stanza.", null=True
            ),
        ),
    ]
