# Generated by Django 5.0.2 on 2024-04-16 15:19

from django.db import migrations, models

import manuscript.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "manuscript",
            "0035_alter_folio_folio_notes_alter_stanza_stanza_notes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanza",
            name="stanza_line_code",
        ),
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_code_ends",
            field=models.CharField(
                blank=True,
                help_text="Indicate where the folio ends. Input the text by book, stanza, and line number. For example: 01.01.07 refers to book 1, stanza 1, line 7.",
                max_length=20,
                null=True,
                validators=[manuscript.models.validate_line_number_code],
            ),
        ),
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_code_starts",
            field=models.CharField(
                blank=True,
                help_text="Indicate where the folio begins. Input the text by book, stanza, and line number. For example: 01.01.01 refers to book 1, stanza 1, line 1.",
                max_length=20,
                null=True,
                validators=[manuscript.models.validate_line_number_code],
            ),
        ),
    ]
