# Generated by Django 5.0.2 on 2024-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0036_remove_stanza_stanza_line_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_variation",
            field=models.CharField(
                blank=True,
                help_text="Indicate any variations in the line (e.g., 'a,' 'b,' etc.).",
                max_length=1,
                null=True,
            ),
        ),
    ]
