# Generated by Django 5.0.2 on 2024-04-16 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0037_stanza_stanza_line_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlemanuscript",
            name="authority_file_url",
        ),
        migrations.CreateModel(
            name="AuthorityFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "authority_file_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL to the authority file for the manuscript.",
                        null=True,
                        verbose_name="Authority File",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="manuscript.singlemanuscript",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authority File",
                "verbose_name_plural": "Authority Files",
            },
        ),
    ]
