# Generated by Django 5.0.2 on 2024-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0038_remove_singlemanuscript_authority_file_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorityfile",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the authority file",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="authorityfile",
            name="authority_file_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the authority file for the manuscript.",
                null=True,
                verbose_name="Authority File URL",
            ),
        ),
    ]
