# Generated by Django 5.0.2 on 2024-04-17 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0039_authorityfile_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="line_code",
            field=models.CharField(
                blank=True, help_text="citation line code", null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="placename_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StanzaVariant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "stanza_variation",
                    models.CharField(
                        blank=True,
                        help_text="The variation in the stanza.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "line_code",
                    models.CharField(
                        blank=True,
                        help_text="The line code for the stanza.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "stanza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="manuscript.stanza",
                    ),
                ),
            ],
        ),
    ]
