# Generated by Django 5.0.2 on 2024-04-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0040_location_line_code_location_placename_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanza",
            name="stanza_line_variation",
        ),
        migrations.AddField(
            model_name="stanza",
            name="stanza_line_variation",
            field=models.ManyToManyField(
                blank=True,
                help_text="Variations in the stanza.",
                related_name="line_variation",
                to="manuscript.stanzavariant",
            ),
        ),
    ]
