# Generated by Django 5.0.2 on 2024-04-17 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0041_remove_stanza_stanza_line_variation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanzavariant",
            name="stanza",
        ),
    ]
