# Generated by Django 5.0.2 on 2024-04-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0042_remove_stanzavariant_stanza"),
    ]

    operations = [
        migrations.AddField(
            model_name="stanzavariant",
            name="variation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lf", "Lines Flipped"),
                    ("dw", "Different Words"),
                    ("do", "Different Order"),
                    ("dp", "Different Punctuation"),
                    ("ds", "Different Spelling"),
                    ("dc", "Different Capitalization"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stanzavariant",
            name="stanza_variation",
            field=models.CharField(
                blank=True,
                help_text="The variation in the stanza.",
                max_length=255,
                null=True,
                verbose_name="Significant Variations",
            ),
        ),
    ]
