# Generated by Django 5.0.2 on 2024-04-25 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0044_remove_stanza_stanza_line_variation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanzavariant",
            name="line_code",
        ),
    ]
