# Generated by Django 5.0.2 on 2024-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0046_alter_stanzavariant_stanza_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="filigree_notes",
            field=models.CharField(
                blank=True,
                max_length=450,
                null=True,
                verbose_name="Flourished/Filigree Initials",
            ),
        ),
        migrations.AlterField(
            model_name="folio",
            name="folio_includes_map",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("yes_toponyms", "Yes with toponyms"),
                    ("yes_no_toponyms", "Yes without toponyms"),
                    ("no", "No"),
                ],
                null=True,
                verbose_name="Does the folio include a map?",
            ),
        ),
    ]
