# Generated by Django 5.0.2 on 2024-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0047_alter_detail_filigree_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialstatus",
            name="siglum",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
