# Generated by Django 5.0.2 on 2024-05-16 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0048_alter_editorialstatus_siglum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editorialstatus",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
    ]
