# Generated by Django 5.0.2 on 2024-05-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0050_alter_folio_manuscript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
        migrations.AlterField(
            model_name="folio",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manuscript.singlemanuscript",
            ),
        ),
        migrations.AlterField(
            model_name="stanza",
            name="related_folio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manuscript.folio",
            ),
        ),
    ]
