# Generated by Django 5.0.2 on 2024-05-16 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0051_alter_detail_manuscript_alter_folio_manuscript_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="standard_water",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detail",
            name="stanzas_ed",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detail",
            name="stanzas_separated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="folio",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
    ]
