# Generated by Django 5.0.2 on 2024-05-16 20:41

import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0052_detail_standard_water_detail_stanzas_ed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="abbreviations_notes",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="book_initials_notes",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="catchwords_notes",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="coat_of_arms_notes",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="distance_numbers_notes",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="filigree_notes",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="stanza_initials_notes",
        ),
        migrations.AlterField(
            model_name="detail",
            name="abbreviations",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="book_headings",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="book_initials",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="catchwords",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="coat_of_arms",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="distance_lines",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="distance_numbers",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="filigree",
            field=models.CharField(
                blank=True,
                max_length=450,
                null=True,
                verbose_name="Flourished/Filigree Initials",
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="laiazzo",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="map_labels",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="stanza_initials",
            field=prose.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="stanzas_separated",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="tabriz",
            field=models.CharField(blank=True, null=True),
        ),
    ]
