# Generated by Django 5.0.2 on 2024-05-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0053_remove_detail_abbreviations_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="is_sea_red",
            field=models.CharField(
                blank=True, null=True, verbose_name="Is the Red Sea colored red?"
            ),
        ),
    ]
