# Generated by Django 5.0.2 on 2024-05-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0054_alter_detail_is_sea_red"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlemanuscript",
            name="digitized_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the digitized manuscript. If there isn't one, leave blank.",
                null=True,
                verbose_name="Digitized URL",
            ),
        ),
    ]
