# Generated by Django 5.0.2 on 2024-05-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0055_alter_singlemanuscript_digitized_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlemanuscript",
            name="digitized_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the digitized manuscript. If there isn't one, leave blank.",
                max_length=500,
                null=True,
                verbose_name="Digitized URL",
            ),
        ),
    ]
