# Generated by Django 5.0.2 on 2024-05-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0056_alter_singlemanuscript_digitized_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlemanuscript",
            name="item_id",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
