# Generated by Django 5.0.2 on 2024-05-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0057_singlemanuscript_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codex",
            name="related_manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
        migrations.AlterField(
            model_name="textdecoration",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
    ]
