# Generated by Django 5.0.2 on 2024-05-17 15:53

import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0058_alter_codex_related_manuscript_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="book_headings_notes",
        ),
        migrations.RemoveField(
            model_name="detail",
            name="map_labels_notes",
        ),
        migrations.AlterField(
            model_name="detail",
            name="book_headings",
            field=prose.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="coat_of_arms",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="distance_numbers",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="map_labels",
            field=prose.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
