# Generated by Django 5.0.2 on 2024-05-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0059_remove_detail_book_headings_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folio",
            name="folio_number",
            field=models.CharField(blank=True, null=True),
        ),
    ]
