# Generated by Django 5.0.2 on 2024-05-17 17:20

from django.db import migrations


def copy_siglum(apps, schema_editor):
    SingleManuscript = apps.get_model("manuscript", "SingleManuscript")
    for manuscript in SingleManuscript.objects.all():
        editorial_status = manuscript.editorialstatus_set.first()
        if editorial_status:
            manuscript.siglum = editorial_status.siglum
            manuscript.save()


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0060_alter_folio_folio_number"),
    ]

    operations = [migrations.RunPython(copy_siglum)]
