# Generated by Django 5.0.2 on 2024-05-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0061_auto_20240517_1320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editorialstatus",
            name="siglum",
        ),
        migrations.AddField(
            model_name="singlemanuscript",
            name="siglum",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
