# Generated by Django 5.0.2 on 2024-05-17 18:05

import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0062_remove_editorialstatus_siglum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="abbreviations",
            field=prose.fields.RichTextField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="author_attribution",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="catchwords",
            field=prose.fields.RichTextField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="coat_of_arms",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="distance_numbers",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="filigree",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Flourished/Filigree Initials",
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="mabel_label",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="map_labels",
            field=prose.fields.RichTextField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="rhodes_status",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="scribe_attribution",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="stanza_headings_marginal_rubrics_notes",
            field=prose.fields.RichTextField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="stanza_initials",
            field=prose.fields.RichTextField(blank=True, max_length=510, null=True),
        ),
    ]
