# Generated by Django 5.0.2 on 2024-05-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0063_alter_detail_abbreviations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlemanuscript",
            name="siglum",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
