# Generated by Django 5.0.2 on 2024-05-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0064_alter_singlemanuscript_siglum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="library",
            options={
                "ordering": ["city", "library"],
                "verbose_name_plural": "Libraries",
            },
        ),
        migrations.AlterModelOptions(
            name="singlemanuscript",
            options={
                "ordering": ["siglum"],
                "verbose_name": "Manuscript",
                "verbose_name_plural": "Manuscripts",
            },
        ),
        migrations.AddField(
            model_name="stanza",
            name="related_manuscript",
            field=models.ForeignKey(
                default=1179,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="library",
            unique_together={("city", "library")},
        ),
    ]
