# Generated by Django 5.0.2 on 2024-05-22 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0066_alter_stanza_related_folio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanzavariant",
            name="variation_type",
        ),
    ]
