# Generated by Django 5.0.2 on 2024-05-22 16:04

from django.db import migrations, models

import manuscript.models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0067_remove_stanzavariant_variation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="stanzavariant",
            name="stanza_variation_line_code_starts",
            field=models.CharField(
                blank=True,
                help_text="Stanza variant line code in the form of '01.01.01a'.",
                max_length=20,
                null=True,
                validators=[manuscript.models.validate_line_number_variant_code],
            ),
        ),
    ]
