# Generated by Django 5.0.2 on 2024-05-23 17:00

import django.db.models.deletion
from django.db import migrations, models

import manuscript.models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0068_stanzavariant_stanza_variation_line_code_starts"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="related_folio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.folio",
            ),
        ),
        migrations.AlterField(
            model_name="stanzavariant",
            name="stanza_variation_line_code_starts",
            field=models.CharField(
                blank=True,
                help_text="Stanza variant line code in the form of '01.01.01a'.",
                max_length=20,
                null=True,
                validators=[manuscript.models.validate_line_number_variant_code],
                verbose_name="Variant line code",
            ),
        ),
    ]
