# Generated by Django 5.0.2 on 2024-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0069_location_related_folio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="line_code",
            field=models.CharField(
                blank=True, help_text="Citation line code.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="placename_id",
            field=models.CharField(blank=True, null=True, verbose_name="Placename ID"),
        ),
    ]
