# Generated by Django 5.0.2 on 2024-05-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0071_alter_folio_options_alter_stanza_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail",
            name="distance_lines",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="is_sea_red",
            field=models.CharField(
                blank=True,
                max_length=510,
                null=True,
                verbose_name="Is the Red Sea colored red?",
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="laiazzo",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="standard_water",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="stanzas_ed",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="stanzas_separated",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="detail",
            name="tabriz",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="editorialstatus",
            name="collated",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="folio",
            name="folio_includes_map",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("yes_toponyms", "Yes with toponyms"),
                    ("yes_no_toponyms", "Yes without toponyms"),
                    ("no", "No"),
                ],
                max_length=510,
                null=True,
                verbose_name="Does the folio include a map?",
            ),
        ),
        migrations.AlterField(
            model_name="folio",
            name="folio_number",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="line_code",
            field=models.CharField(
                blank=True, help_text="Citation line code.", max_length=510, null=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="placename_id",
            field=models.CharField(
                blank=True, max_length=510, null=True, verbose_name="Placename ID"
            ),
        ),
        migrations.AlterField(
            model_name="textdecoration",
            name="diagrams",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="textdecoration",
            name="illumination",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="textdecoration",
            name="maps",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name="textdecoration",
            name="white_vine_work",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
