# Generated by Django 5.0.2 on 2024-06-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0073_alter_stanzavariant_stanza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stanzavariant",
            name="stanza",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.stanza",
            ),
        ),
    ]
