# Generated by Django 5.0.2 on 2024-06-07 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0074_alter_stanzavariant_stanza"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="related_folio",
        ),
    ]
