# Generated by Django 5.0.2 on 2024-06-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0075_remove_location_related_folio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="editorialstatus",
            old_name="group",
            new_name="decorative_group",
        ),
        migrations.AddField(
            model_name="detail",
            name="diagram_sun",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name="detail",
            name="gion_in_egypt",
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name="editorialstatus",
            name="map_group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
