# Generated by Django 5.0.2 on 2024-06-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0075_remove_location_related_folio"),
    ]

    operations = [
        migrations.AddField(
            model_name="stanzavariant",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("it", "Italian")],
                max_length=2,
                null=True,
            ),
        ),
    ]
