# Generated by Django 5.0.2 on 2024-06-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0076_stanzavariant_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stanzavariant",
            name="language",
        ),
        migrations.AddField(
            model_name="stanza",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("it", "Italian"),
                    ("la", "Latin"),
                    ("fr", "French"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
