# Generated by Django 5.0.2 on 2024-06-13 18:09

import django.db.models.deletion
import prose.fields
from django.db import migrations, models

import manuscript.models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0077_remove_stanzavariant_language_stanza_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="StanzaTranslated",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "line_code_starts",
                    models.CharField(
                        blank=True,
                        help_text="Indicate where the stanza begins. Input the text by book, stanza, and line number. For example: 01.01.01 refers to book 1, stanza 1, line 1.",
                        max_length=20,
                        null=True,
                        validators=[manuscript.models.validate_line_number_code],
                    ),
                ),
                (
                    "line_code_ends",
                    models.CharField(
                        blank=True,
                        help_text="Indicate where the stanza ends. Input the text by book, stanza, and line number. For example: 01.01.07 refers to book 1, stanza 1, line 7.",
                        max_length=20,
                        null=True,
                        validators=[manuscript.models.validate_line_number_code],
                    ),
                ),
                (
                    "stanza_translation",
                    prose.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("it", "Italian"),
                            ("la", "Latin"),
                            ("fr", "French"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "stanza",
                    models.ForeignKey(
                        help_text="The stanza to which the translation belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manuscript.stanza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stanza Translation",
                "verbose_name_plural": "Stanza Translations",
            },
        ),
    ]
