# Generated by Django 5.0.2 on 2024-06-13 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0078_stanzatranslated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stanzatranslated",
            old_name="line_code_ends",
            new_name="stanza_line_code_ends",
        ),
        migrations.RenameField(
            model_name="stanzatranslated",
            old_name="line_code_starts",
            new_name="stanza_line_code_starts",
        ),
    ]
