# Generated by Django 5.0.2 on 2024-06-13 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "manuscript",
            "0079_rename_line_code_ends_stanzatranslated_stanza_line_code_ends_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stanzatranslated",
            old_name="stanza_translation",
            new_name="stanza_text",
        ),
    ]
