# Generated by Django 5.0.2 on 2024-06-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0080_rename_stanza_translation_stanzatranslated_stanza_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="related_folio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.folio",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="related_manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
    ]
