# Generated by Django 5.0.2 on 2024-06-13 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0081_location_related_folio_location_related_manuscript"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="related_manuscript",
        ),
    ]
