# Generated by Django 5.0.2 on 2024-06-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0083_remove_location_related_folio_location_related_folio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="related_folio",
            field=models.ManyToManyField(
                blank=True,
                help_text="The folio where the toponym is mentioned.",
                to="manuscript.folio",
            ),
        ),
    ]
