# Generated by Django 5.0.2 on 2024-07-25 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0076_rename_group_editorialstatus_decorative_group_and_more"),
        ("manuscript", "0085_remove_location_related_folio"),
    ]

    operations = []
