# Generated by Django 5.0.2 on 2024-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0086_merge_20240725_0846"),
    ]

    operations = [
        migrations.AddField(
            model_name="singlemanuscript",
            name="photographs",
            field=models.FileField(
                blank=True,
                help_text="Upload photographs of the manuscript.",
                null=True,
                upload_to="",
            ),
        ),
    ]
