# Generated by Django 5.0.2 on 2024-07-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0088_alter_singlemanuscript_siglum"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="code_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Code ID"
            ),
        ),
    ]
