# Generated by Django 5.0.2 on 2024-07-25 15:34

from django.db import migrations, models

import manuscript.models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0089_location_code_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Input the text by book, stanza, and line number. For example: 01.01.01 refers to book 1, stanza 1, line 1.",
                        max_length=255,
                        null=True,
                        validators=[manuscript.models.validate_line_number_code],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="location",
            name="line_code",
        ),
        migrations.AddField(
            model_name="location",
            name="line_code",
            field=models.ManyToManyField(
                blank=True,
                help_text="Citation line codes where the toponym appears.",
                to="manuscript.linecode",
            ),
        ),
    ]
