# Generated by Django 5.0.2 on 2024-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0090_linecode_remove_location_line_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linecode",
            name="associated_iiif_url",
            field=models.URLField(
                blank=True,
                help_text="The URL to the IIIF manifest for the manuscript. If there isn't one, leave blank.",
                max_length=255,
                null=True,
                verbose_name="Associated IIIF URL",
            ),
        ),
    ]
