# Generated by Django 5.0.2 on 2024-07-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0091_linecode_associated_iiif_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stanzatranslated",
            options={
                "verbose_name": "Stanza translation",
                "verbose_name_plural": "Stanza translations",
            },
        ),
        migrations.AddField(
            model_name="location",
            name="toponym_type",
            field=models.CharField(
                blank=True,
                choices=[("mp", "Map"), ("pm", "Poem")],
                max_length=2,
                null=True,
            ),
        ),
    ]
