# Generated by Django 5.0.2 on 2024-07-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0092_alter_stanzatranslated_options_location_toponym_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="code_id",
        ),
        migrations.AlterField(
            model_name="location",
            name="toponym_type",
            field=models.CharField(
                blank=True,
                choices=[("mp", "Map"), ("pm", "Poem")],
                help_text="The type will be automatically set based off the placename ID.",
                max_length=2,
                null=True,
            ),
        ),
    ]
