# Generated by Django 5.0.2 on 2024-08-19 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0093_remove_location_code_id_alter_location_toponym_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="line_code",
        ),
        migrations.AddField(
            model_name="location",
            name="line_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Citation line codes where the toponym appears.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manuscript.linecode",
            ),
        ),
    ]
