# Generated by Django 5.0.2 on 2024-08-19 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0094_remove_location_line_code_location_line_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="line_code",
        ),
        migrations.AddField(
            model_name="linecode",
            name="associated_toponym",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.location",
            ),
        ),
    ]
