# Generated by Django 5.0.2 on 2024-08-20 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0096_linecode_associated_folio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linecode",
            name="associated_folio",
        ),
    ]
