# Generated by Django 5.0.2 on 2024-08-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0098_linecode_associated_folio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Modern location"
            ),
        ),
    ]
