# Generated by Django 5.0.2 on 2024-09-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0100_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="modern_country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Modern Country"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="place_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
