# Generated by Django 5.0.2 on 2024-09-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0101_location_modern_country_location_place_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationalias",
            name="placename_ancient",
            field=models.CharField(
                blank=True,
                help_text="The ancient name of the placename.",
                max_length=255,
                null=True,
                verbose_name="Ancient placename",
            ),
        ),
    ]
