# Generated by Django 5.0.2 on 2024-12-17 19:03

from django.db import migrations, models

import manuscript.models


class Migration(migrations.Migration):
    dependencies = [
        ("manuscript", "0102_locationalias_placename_ancient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editorialstatus",
            name="iiif_url",
        ),
        migrations.AddField(
            model_name="folio",
            name="line_code_range_end",
            field=models.CharField(
                blank=True,
                help_text="Input the text by book, stanza, and line number. For example: 01.01.01 refers to book 1, stanza 1, line 1.",
                max_length=100,
                null=True,
                validators=[manuscript.models.validate_line_number_code],
            ),
        ),
        migrations.AddField(
            model_name="folio",
            name="line_code_range_start",
            field=models.CharField(
                blank=True,
                help_text="Input the text by book, stanza, and line number. For example: 01.01.01 refers to book 1, stanza 1, line 1.",
                max_length=100,
                null=True,
                validators=[manuscript.models.validate_line_number_code],
            ),
        ),
    ]
