# Generated by Django 5.0.2 on 2025-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0103_remove_editorialstatus_iiif_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stanza',
            name='related_folio',
        ),
        migrations.AddField(
            model_name='stanza',
            name='folios',
            field=models.ManyToManyField(blank=True, help_text='The folios on which this stanza appears.', related_name='stanzas', to='manuscript.folio'),
        ),
    ]
