# Generated by Django 5.0.2 on 2025-01-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0104_remove_stanza_related_folio_stanza_folios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stanza',
            name='related_manuscript',
        ),
    ]
