# Generated by Django 5.0.2 on 2025-02-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0105_remove_stanza_related_manuscript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationalias',
            options={'ordering': ['placename_standardized'], 'verbose_name': 'Toponym Alias', 'verbose_name_plural': 'Toponym Aliases'},
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
