# Generated by Django 5.0.2 on 2025-02-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0106_alter_locationalias_options_location_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationalias',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='locationalias',
            name='folio',
            field=models.CharField(blank=True, help_text='The folio where this variant appears.', max_length=255, null=True, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='locationalias',
            name='manuscript',
            field=models.CharField(blank=True, help_text='The manuscript where this variant appears.', max_length=255, null=True, verbose_name='Manuscript'),
        ),
        migrations.AlterUniqueTogether(
            name='locationalias',
            unique_together={('location', 'placename_from_mss', 'manuscript', 'folio')},
        ),
    ]
