# Generated by Django 5.0.2 on 2025-02-04 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0107_alter_locationalias_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationalias',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='locationalias',
            name='folio',
            field=models.ForeignKey(blank=True, help_text='The folio where this variant appears.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscript.folio', verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='locationalias',
            name='manuscript',
            field=models.ForeignKey(blank=True, help_text='The manuscript where this variant appears.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscript.singlemanuscript', verbose_name='Manuscript'),
        ),
        migrations.AlterUniqueTogether(
            name='locationalias',
            unique_together={('location', 'placename_alias', 'manuscript', 'folio')},
        ),
    ]
