# Generated by Django 5.0.2 on 2025-02-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0108_alter_locationalias_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationalias',
            name='folio',
            field=models.CharField(blank=True, help_text='The folio where this variant appears.', max_length=255, null=True, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='locationalias',
            name='manuscript',
            field=models.CharField(blank=True, help_text='The manuscript where this variant appears.', max_length=255, null=True, verbose_name='Manuscript'),
        ),
    ]
