# Generated by Django 5.0.2 on 2025-02-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscript', '0109_alter_locationalias_folio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationalias',
            name='folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscript.folio'),
        ),
        migrations.AlterField(
            model_name='locationalias',
            name='manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manuscript.singlemanuscript'),
        ),
    ]
