# Generated by Django 5.0.2 on 2025-02-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0111_alter_locationalias_folio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationalias",
            name="folio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.folio",
            ),
        ),
        migrations.AlterField(
            model_name="locationalias",
            name="manuscript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.singlemanuscript",
            ),
        ),
    ]
