# Generated by Django 5.0.2 on 2025-02-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0112_alter_locationalias_folio_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="locationalias",
            unique_together={("location", "placename_alias")},
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="folio",
        ),
        migrations.RemoveField(
            model_name="locationalias",
            name="manuscript",
        ),
        migrations.AddField(
            model_name="locationalias",
            name="folio",
            field=models.ManyToManyField(blank=True, to="manuscript.folio"),
        ),
        migrations.AddField(
            model_name="locationalias",
            name="manuscript",
            field=models.ManyToManyField(blank=True, to="manuscript.singlemanuscript"),
        ),
    ]
