# Generated by Django 5.0.2 on 2025-02-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0113_alter_locationalias_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locationalias",
            old_name="folio",
            new_name="folios",
        ),
        migrations.RenameField(
            model_name="locationalias",
            old_name="manuscript",
            new_name="manuscripts",
        ),
    ]
