# Generated by Django 5.0.2 on 2025-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0114_rename_folio_locationalias_folios_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linecode",
            name="associated_toponym",
        ),
        migrations.AddField(
            model_name="linecode",
            name="associated_toponyms",
            field=models.ManyToManyField(
                blank=True,
                help_text="The toponyms (locations) mentioned in this line.",
                related_name="line_codes",
                to="manuscript.location",
                verbose_name="Associated Toponyms",
            ),
        ),
    ]
