# Generated by Django 5.1.7 on 2025-03-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuscript", "0115_remove_linecode_associated_toponym_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linecode",
            options={
                "ordering": ["code"],
                "verbose_name": "Line Code",
                "verbose_name_plural": "Line Codes",
            },
        ),
        migrations.AlterField(
            model_name="linecode",
            name="associated_folio",
            field=models.ForeignKey(
                blank=True,
                help_text="The folio where this line code appears.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manuscript.folio",
                verbose_name="Associated Folio",
            ),
        ),
    ]
